### ISSUE TITLE
[QST] What's the relationship between this project and the official nvidia ngc isaac_ros_deb_base container.

### ISSUE THREAD

**Issue by ZhenshengLee** [rbonghi/isaac_ros_base#11]
First of all I would say it's a great project to help us create docker images to run issac_ros.

At the same time, there is a official container which is published without dockerfile in ngc catlog, which is https://catalog.ngc.nvidia.com/orgs/nvidia/teams/isaac/containers/ros , and is recommended in https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.x86_64.ros2_humble so developers can use it freely(without the dockerfile!).

Does this project have any relationship with the nvidia version of container?

1. Does this project try to reverse-engineering the closed source ngc version?
2. Or it is just a standalone project that will get its own path.

Thanks!

**Comment by rbonghi** [comment]
Hi @ZhenshengLee 
This repository was made before the official NVIDIA containers.
Now it's outdated and I suggest to use the NVIDIA documentation https://nvidia-isaac-ros.github.io/index.html
